### ISSUE TITLE
Docs site is missing

### ISSUE THREAD

**Issue by bribroder** [ContainerSSH/containerssh.github.io#49]
Github 404 page: https://containerssh.io

![Screenshot 2023-09-05 at 23 03 55](https://github.com/ContainerSSH/containerssh.github.io/assets/1398891/cd573907-018b-4f24-862a-78c8dd2d3ddd)

**Comment by tsipinakis** [comment]
Should be fixed now, thanks for the report! Slight hiccup when deploying #48 .
